### ISSUE TITLE
Reloading Race Condition

### ISSUE THREAD

**Issue by jfeaver** [fxn/zeitwerk#107]
I was running into periodic `NameError: uninitialized constant` errors. I kept at it and eventually learned about `loader.log!` which led to my conclusion that a reload was starting before a running thread was completed.

The log looks like this:

```
172.18.0.1 - - [06/Feb/2020:20:28:52 +0000] "GET /exam_finished?token=test-token&user_gid=xxxx HTTP/1.1" 200 470 0.0516
Zeitwerk@4043d0: autoload for Types removed
Zeitwerk@4043d0: autoload for ApplicationService removed
Zeitwerk@4043d0: autoload for GetsExamUrl removed
Zeitwerk@4043d0: autoload for GetsExamResult removed
Zeitwerk@4043d0: autoload for ApiResult removed
Zeitwerk@4043d0: file /app/app/my_app/my_app.rb is ignored because MyApp is already defined
Zeitwerk@4043d0: file /app/app/my_app/settings.rb is ignored because Settings is already defined
Zeitwerk@4043d0: autoload set for Types, to be loaded from /app/app/my_app/types.rb
Zeitwerk@4043d0: autoload set for ApplicationService, to be loaded from /app/app/services/application_service.rb
Zeitwerk@4043d0: autoload set for GetsExamUrl, to be loaded from /app/app/services/gets_exam_url.rb
Zeitwerk@4043d0: autoload set for GetsExamResult, to be loaded from /app/app/services/gets_exam_result.rb
Zeitwerk@4043d0: autoload set for ApiResult, to be loaded from /app/external/api_result.rb
Zeitwerk@4043d0: autoload for Types removed
Zeitwerk@4043d0: autoload for ApplicationService removed
Zeitwerk@4043d0: autoload for GetsExamUrl removed
Zeitwerk@4043d0: autoload for GetsExamResult removed
Zeitwerk@4043d0: autoload for ApiResult removed
172.18.0.1 - - [06/Feb/2020:20:28:52 +0000] "GET /styles.css HTTP/1.1" 200 1564 0.0518
Zeitwerk@4043d0: file /app/app/my_app/my_app.rb is ignored because MyApp is already defined
Zeitwerk@4043d0: file /app/app/my_app/settings.rb is ignored because Settings is already defined
Zeitwerk@4043d0: autoload set for Types, to be loaded from /app/app/my_app/types.rb
Zeitwerk@4043d0: autoload set for ApplicationService, to be loaded from /app/app/services/application_service.rb
Zeitwerk@4043d0: autoload set for GetsExamUrl, to be loaded from /app/app/services/gets_exam_url.rb
Zeitwerk@4043d0: autoload set for GetsExamResult, to be loaded from /app/app/services/gets_exam_result.rb
Zeitwerk@4043d0: autoload set for ApiResult, to be loaded from /app/external/api_result.rb
Zeitwerk@4043d0: autoload for Types removed
Zeitwerk@4043d0: autoload for ApplicationService removed
Zeitwerk@4043d0: autoload for GetsExamUrl removed
Zeitwerk@4043d0: autoload for GetsExamResult removed
Zeitwerk@4043d0: autoload for ApiResult removed
172.18.0.1 - - [06/Feb/2020:20:28:52 +0000] "GET /javascripts/my_app.js HTTP/1.1" 200 149 0.0816
Zeitwerk@4043d0: file /app/app/my_app/my_app.rb is ignored because MyApp is already defined
Zeitwerk@4043d0: file /app/app/my_app/settings.rb is ignored because Settings is already defined
Zeitwerk@4043d0: autoload set for Types, to be loaded from /app/app/my_app/types.rb
Zeitwerk@4043d0: autoload set for ApplicationService, to be loaded from /app/app/services/application_service.rb
Zeitwerk@4043d0: autoload set for GetsExamUrl, to be loaded from /app/app/services/gets_exam_url.rb
Zeitwerk@4043d0: autoload set for GetsExamResult, to be loaded from /app/app/services/gets_exam_result.rb
Zeitwerk@4043d0: autoload set for ApiResult, to be loaded from /app/external/api_result.rb
172.18.0.1 - - [06/Feb/2020:20:28:52 +0000] "GET /javascripts/exam_finished.js HTTP/1.1" 200 140605 0.1234
Zeitwerk@4043d0: autoload for Types removed
Zeitwerk@4043d0: autoload for ApplicationService removed
Zeitwerk@4043d0: autoload for GetsExamUrl removed
Zeitwerk@4043d0: autoload for GetsExamResult removed
Zeitwerk@4043d0: autoload for ApiResult removed
Zeitwerk@4043d0: file /app/app/my_app/my_app.rb is ignored because MyApp is already defined
Zeitwerk@4043d0: file /app/app/my_app/settings.rb is ignored because Settings is already defined
Zeitwerk@4043d0: autoload set for Types, to be loaded from /app/app/my_app/types.rb
Zeitwerk@4043d0: autoload set for ApplicationService, to be loaded from /app/app/services/application_service.rb
Zeitwerk@4043d0: autoload set for GetsExamUrl, to be loaded from /app/app/services/gets_exam_url.rb
Zeitwerk@4043d0: autoload set for GetsExamResult, to be loaded from /app/app/services/gets_exam_result.rb
Zeitwerk@4043d0: autoload set for ApiResult, to be loaded from /app/external/api_result.rb
Zeitwerk@4043d0: autoload for Types removed
Zeitwerk@4043d0: autoload for ApplicationService removed
Zeitwerk@4043d0: autoload for GetsExamUrl removed
Zeitwerk@4043d0: autoload for GetsExamResult removed
Zeitwerk@4043d0: autoload for ApiResult removed
2020-02-06 20:28:52 - NameError - uninitialized constant ApplicationService:
        /app/app/services/gets_exam_result.rb:2:in `<top (required)>'
        /bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:16:in `require'
        /bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:16:in `require'
        /app/web/server.rb:80:in `get_exam_result'
        ...
```

In the logs, you can see various web requests being made in quick succession (I was hard reloading in my web browser so all resources on the page were being requested rapidly). Then, just before the error happens, the constant that is erroring has it's autoload removed. I believe the latest incoming request is unloading while some other request is still in progress.

Background: I'm using Zeitwerk with a small Sinatra application.

I want Zeitwerk to either have Zeitwerk completely take care of this for me or have some configuration value to only allow reloading every X seconds or something. Maybe this is just a gotcha that should be documented somewhere.

**Comment by fxn** [comment]
Have you read https://github.com/fxn/zeitwerk#reloading?

**Comment by jfeaver** [comment]
I had. Rereading it now did help. Thanks!

For future viewers, the Zeitwerk README mentions thread safety is not provided by Zeitwerk. Instead, you should work with the framework and use a "write lock" (of a read/write lock implementation) and wrap the `loader.reload` method. Sinatra does not provide a Read/Write lock (from what I can see) so implementing one using the concurrent-ruby gem looks like the way to go.

https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent-ruby/concurrent/atomic/read_write_lock.rb

Something like this perhaps:

```ruby
lock = Concurrent::ReadWriteLock.new

before do
  lock.with_write_lock { loader.reload }
end
```
