### ISSUE TITLE
autoloading "Helpers-like" modules

### ISSUE THREAD

**Issue by mickael-palma-argus** [fxn/zeitwerk#13]
Hi,

Here is the folder tree my gem has:
```
lib
├── active_storage
│   ├── openstack
│   │   ├── client
│   │   │   ├── authenticator
│   │   │   │   └── request.rb
│   │   │   ├── authenticator.rb
│   │   │   ├── storage
│   │   │   │   ├── delete_object.rb
│   │   │   │   ├── get_object.rb
│   │   │   │   ├── list_objects.rb
│   │   │   │   ├── object_store_url.rb
│   │   │   │   ├── put_object.rb
│   │   │   │   └── show_object_metadata.rb
│   │   │   └── storage.rb
│   │   ├── client.rb
│   │   ├── helpers
│   │   │   ├── cache_readerable.rb
│   │   │   ├── cacheable_body.rb
│   │   │   └── https_client.rb
│   │   ├── railtie.rb
│   │   └── version.rb
│   └── service
│       └── openstack_service.rb
└── activestorage_openstack.rb
```

In the activestorage_openstack.rb file I put:
```
require 'zeitwerk'
Zeitwerk::Loader.for_gem.setup
```

In the authenticator.rb file, I have:
```
require_relative '../helpers/cache_readerable'

module ActiveStorage
  module Openstack
    class Client
      class Authenticator
        include Helpers::CacheReaderable
        [...]
      end
    end
  end
end
```

I want to get rid of the require_relative directive but without it I get this error:
```
NameError:
  uninitialized constant ActiveStorage::Openstack::Helpers::CacheReaderable
```

Any suggestions?

Thank you for the work so far.

**Comment by fxn** [comment]
If the information is not sensitive, could you enable logging and trigger that error with a minimal number of steps?

```ruby
require 'zeitwerk'
loader = Zeitwerk::Loader.for_gem
loader.logger = method(:puts)
loader.setup
```

**Comment by mickael-palma-argus** [comment]
Here is the output:

```
Zeitwerk@activestorage_openstack: autoload set for ActivestorageOpenstack, to be loaded from /app/lib/activestorage_openstack.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Railtie, to be loaded from /app/lib/active_storage/openstack/railtie.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client, to be loaded from /app/lib/active_storage/openstack/client.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Version, to be loaded from /app/lib/active_storage/openstack/version.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Helpers, to be autovivified from /app/lib/active_storage/openstack/helpers
```

Does it help ?

**Comment by fxn** [comment]
What did you run to get this output? The NameError came right after that last line?

**Comment by mickael-palma-argus** [comment]
Here is the full Rspec output with the error:

```
15:30:15 - INFO - Running: spec/lib/active_storage/openstack/client/authenticator_spec.rb
Running via Spring preloader in process 5076
Zeitwerk@activestorage_openstack: autoload set for ActivestorageOpenstack, to be loaded from /app/lib/activestorage_openstack.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Railtie, to be loaded from /app/lib/active_storage/openstack/railtie.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client, to be loaded from /app/lib/active_storage/openstack/client.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Version, to be loaded from /app/lib/active_storage/openstack/version.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Helpers, to be autovivified from /app/lib/active_storage/openstack/helpers
                                                                                                                                        
An error occurred while loading ./spec/lib/active_storage/openstack/client/authenticator_spec.rb.
Failure/Error: include Helpers::CacheReaderable

NameError:
  uninitialized constant ActiveStorage::Openstack::Helpers::CacheReaderable
# ./lib/active_storage/openstack/client/authenticator.rb:13:in `<class:Authenticator>'
# ./lib/active_storage/openstack/client/authenticator.rb:10:in `<class:Client>'
# ./lib/active_storage/openstack/client/authenticator.rb:8:in `<module:Openstack>'
# ./lib/active_storage/openstack/client/authenticator.rb:7:in `<module:ActiveStorage>'
# ./lib/active_storage/openstack/client/authenticator.rb:6:in `<top (required)>'
# ./spec/lib/active_storage/openstack/client/authenticator_spec.rb:3:in `<top (required)>'
# /usr/local/bundle/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
# -e:1:in `<main>'
Run options: include {:focus=>true}                                                                                                     
                                                                                                                                        
All examples were filtered out; ignoring {:focus=>true}
No examples found.                                                                                                                      
 0/0 |===================================================== 100 ======================================================>| Time: 00:00:00 

Finished in 0.19568 seconds (files took 8.47 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

15:30:24 - INFO - Guard::RSpec has failed, other group's plugins will be skipped.
[1] Red_green_refactor guard(main)>
```

**Comment by mickael-palma-argus** [comment]
If it helps, here is the gem I'm working on: https://github.com/mickael-palma-argus/activestorage-openstack

**Comment by fxn** [comment]
Cannot reproduce here:

```
$ bundle exec rspec spec/lib/active_storage/openstack/client/authenticator_spec.rb
...
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Storage, to be loaded from /Users/fxn/tmp/activestorage-openstack/lib/active_storage/openstack/client/storage.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Authenticator, to be loaded from /Users/fxn/tmp/activestorage-openstack/lib/active_storage/openstack/client/authenticator.rb
Zeitwerk@activestorage_openstack: constant ActiveStorage::Openstack::Client loaded from file /Users/fxn/tmp/activestorage-openstack/lib/active_storage/openstack/client.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Authenticator::Request, to be loaded from /Users/fxn/tmp/activestorage-openstack/lib/active_storage/openstack/client/authenticator/request.rb
Zeitwerk@activestorage_openstack: module ActiveStorage::Openstack::Helpers autovivified from directory /Users/fxn/tmp/activestorage-openstack/lib/active_storage/openstack/helpers
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Helpers::CacheableBody, to be loaded from /Users/fxn/tmp/activestorage-openstack/lib/active_storage/openstack/helpers/cacheable_body.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Helpers::HttpsClient, to be loaded from /Users/fxn/tmp/activestorage-openstack/lib/active_storage/openstack/helpers/https_client.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Helpers::CacheReaderable, to be loaded from /Users/fxn/tmp/activestorage-openstack/lib/active_storage/openstack/helpers/cache_readerable.rb
Zeitwerk@activestorage_openstack: constant ActiveStorage::Openstack::Helpers::CacheReaderable loaded from file /Users/fxn/tmp/activestorage-openstack/lib/active_storage/openstack/helpers/cache_readerable.rb
...
```

The last line there is the one that loads that file.

What do you exactly run?

**Comment by mickael-palma-argus** [comment]
I found the root of the problem: spring

I had to stop it to make it work.

Now I have another problem with inflection:
```
16:45:06 - INFO - Run all
16:45:06 - INFO - Running all specs
Running via Spring preloader in process 604
"activestorage_openstack"
"active_storage"
"openstack"
"railtie"
"client"
"version"
"client"
"helpers"
"service"
"support"
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Storage, to be loaded from /app/lib/active_storage/openstack/client/storage.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Authenticator, to be loaded from /app/lib/active_storage/openstack/client/authenticator.rb
Zeitwerk@activestorage_openstack: constant ActiveStorage::Openstack::Client loaded from file /app/lib/active_storage/openstack/client.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Authenticator::Request, to be loaded from /app/lib/active_storage/openstack/client/authenticator/request.rb
Zeitwerk@activestorage_openstack: module ActiveStorage::Openstack::Helpers autovivified from directory /app/lib/active_storage/openstack/helpers
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Helpers::CacheableBody, to be loaded from /app/lib/active_storage/openstack/helpers/cacheable_body.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Helpers::HttpsClient, to be loaded from /app/lib/active_storage/openstack/helpers/https_client.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Helpers::CacheReaderable, to be loaded from /app/lib/active_storage/openstack/helpers/cache_readerable.rb
Zeitwerk@activestorage_openstack: constant ActiveStorage::Openstack::Helpers::CacheReaderable loaded from file /app/lib/active_storage/openstack/helpers/cache_readerable.rb
Zeitwerk@activestorage_openstack: constant ActiveStorage::Openstack::Client::Authenticator loaded from file /app/lib/active_storage/openstack/client/authenticator.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Storage::ListObjects, to be loaded from /app/lib/active_storage/openstack/client/storage/list_objects.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Storage::GetObject, to be loaded from /app/lib/active_storage/openstack/client/storage/get_object.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Storage::ShowObjectMetadata, to be loaded from /app/lib/active_storage/openstack/client/storage/show_object_metadata.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Storage::PutObject, to be loaded from /app/lib/active_storage/openstack/client/storage/put_object.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Storage::Object, to be loaded from /app/lib/active_storage/openstack/client/storage/object.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Storage::ObjectStoreUrl, to be loaded from /app/lib/active_storage/openstack/client/storage/object_store_url.rb
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Client::Storage::DeleteObject, to be loaded from /app/lib/active_storage/openstack/client/storage/delete_object.rb
                                                                                                                                                                                                                                                     
An error occurred while loading ./spec/lib/active_storage/openstack/client/storage_spec.rb.
Failure/Error: include Helpers::HTTPSClient

NameError:
  uninitialized constant ActiveStorage::Openstack::Helpers::HTTPSClient
# ./lib/active_storage/openstack/client/storage.rb:11:in `<class:Storage>'
# ./lib/active_storage/openstack/client/storage.rb:8:in `<class:Client>'
# ./lib/active_storage/openstack/client/storage.rb:6:in `<module:Openstack>'
# ./lib/active_storage/openstack/client/storage.rb:4:in `<module:ActiveStorage>'
# ./lib/active_storage/openstack/client/storage.rb:3:in `<top (required)>'
# /usr/local/bundle/gems/zeitwerk-1.3.1/lib/zeitwerk/kernel.rb:23:in `require'
# /usr/local/bundle/gems/zeitwerk-1.3.1/lib/zeitwerk/kernel.rb:23:in `require'
# ./spec/lib/active_storage/openstack/client/storage_spec.rb:5:in `<top (required)>'
# /usr/local/bundle/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
# -e:1:in `<main>'
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Service::OpenstackService, to be loaded from /app/lib/active_storage/service/openstack_service.rb
Zeitwerk@activestorage_openstack: constant ActiveStorage::Service::OpenstackService loaded from file /app/lib/active_storage/service/openstack_service.rb
Run options: include {:focus=>true}                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                     
All examples were filtered out; ignoring {:focus=>true}
 0/16 |>                                                                                                                                                                                                                            |  ETA: ??:??:?? 
Finished in 0.12562 seconds (files took 8.16 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

16:45:15 - INFO - Guard::RSpec has failed, other group's plugins will be skipped.
```

With this Inflector:

```
# frozen_string_literal: true

require 'zeitwerk'

# Inflector for Zeitwerk
class CustomInflector < Zeitwerk::Inflector
  def camelize(basename, _abspath)
    p basename
    case basename
    when 'https_client'
      "HTTPSClient"
    else
      super
    end
  end
end
```

As you can see the inflector scan the helpers folder but not the files in it.
So https_client it is never caught.

**Comment by fxn** [comment]
Good! We are moving forward!

I see this in the traces:

```
Zeitwerk@activestorage_openstack: autoload set for ActiveStorage::Openstack::Helpers::HttpsClient, to be loaded from /app/lib/active_storage/openstack/helpers/https_client.rb
```

That means the file has been scanned, but the inflector has not inflected the basename. Are you setting the inflector? Maybe spring again?

**Comment by mickael-palma-argus** [comment]
The output you see:
```
"activestorage_openstack"
"active_storage"
"openstack"
"railtie"
"client"
"version"
"client"
"helpers"
"service"
"support"
```

means my inflector is taking over

**Comment by fxn** [comment]
Oh, yes, that is right. But on the other hand the `p` stops working for some reason. That is, we don't see

```
"authenticator"
```

For example. Could you please

```
$ spring stop
$ export DISABLE_SPRING=1
```

while debugging this? Would like to remove spring completely from the equation since it was the cause of the first problem.

**Comment by mickael-palma-argus** [comment]
I found the solution

I must not use the for_gem method.
But this instead:
```
require_relative 'support/zeitwerk'

loader = Zeitwerk::Loader.new
loader.inflector = CustomInflector.new
loader.push_dir(__dir__)
# loader.logger = method(:puts) # For debug
loader.setup
```

and in my support/zeitwerk.rb:
```
# frozen_string_literal: true

require 'zeitwerk'

# Inflector for Zeitwerk
class CustomInflector < Zeitwerk::Inflector
  def camelize(basename, _abspath)
    case basename
    when 'https_client'
      'HTTPSClient'
    else
      super
    end
  end
end
```

The only way to override the for_gem inflector (Zeitwerk::GemInflector) is using Ruby refine like this:
```
# frozen_string_literal: true

require 'zeitwerk'

module CustomInflector
  refine Zeitwerk::GemInflector do
    def camelize(basename, _abspath)
      case basename
      when 'https_client'
        'HTTPSClient'
      else
        super
      end
    end
  end
end

using CustomInflector

loader = Zeitwerk::Loader.for_gem
# loader.inflector = CustomInflector.new
# loader.push_dir(__dir__)
# loader.logger = method(:puts) # For debug
loader.setup
```

**Comment by fxn** [comment]
You can also do this:

```ruby
# Nice extracting some code here.
require_relative 'support/zeitwerk'

loader = Zeitwerk::Loader.for_gem
loader.inflector = CustomInflector.new
loader.ignore(__FILE__) # this file does not define ActivetorageOpenstack
loader.setup
```

**Comment by fxn** [comment]
The important bit is that `loader` has to have the correct inflector set before the call to `setup`. The default inflector doesn't matter if you override it.

**Comment by mickael-palma-argus** [comment]
I understand.

Thank you for you support.

Keep up the good stuff 👍

**Comment by fxn** [comment]
Awesome, thanks for the prompt debugging session!

**Comment by fxn** [comment]
Oh, BTW, I saw the code issues some `autoload` calls like `autoload :Request`. You can remove those too and the Active Support module for them.

**Comment by mickael-palma-argus** [comment]
Even better !!

**Comment by mickael-palma-argus** [comment]
I had to add a new condition to the inflector though:

```ruby
# Inflector for Zeitwerk
class CustomInflector < Zeitwerk::Inflector
  # :reek:ControlParameter
  def camelize(basename, _abspath)
    case basename
    when 'https_client'
      'HTTPSClient'
    when 'object_store_url'
      'ObjectStoreURL'
    else
      super
    end
  end
end
```

**Comment by fxn** [comment]
Makes sense, the inflector will need as many exceptions as the code base has (or else change the constant, but those two look better as they are).
