### ISSUE TITLE
Zeitwork hack on require method, which cause issue.

### ISSUE THREAD

**Issue by zw963** [fxn/zeitwerk#196]
It hard to describe this issue, just give a example.

I use roda + sequel for my own web project, so, basially, i create almost every things from scratch (compare to ruby on rails)

I add a `bin/console`, for use like `rails console`, but support use pry( development) or irb (production).

it code like this:

```rb
require_relative '../config/environment'

DB.transaction do
  unless ARGV[0] == '--no-sandbox'
    DB.rollback_on_exit
    warn 'Running console on sandbox mode.'
  end

  ARGV.delete('--no-sandbox')

  begin
    $0 = 'pry'
    require 'pry'
    opts = Pry::CLI.parse_options
    Pry::CLI.start(opts)
  rescue LoadError
    require 'irb'
    IRB.start(__FILE__)
  end
end
```

It works!

But the issue is, but use on production, it start irb as REPL.

but when some error raising. i get following unexpected backtrace.

What i means is this line, please check following backtrace.

zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- pry (LoadError)
Did you mean?  pty

```sh
[deployer@zw963 current]$ bin/console 
RACK_ENV=production
DB connected: postgres://postgres:temp1234@127.0.0.1:5432/marketbet_crawler_production
Eager loading ...
Running console on sandbox mode.
3.0.0 :001 > abcd
(irb):1:in `<main>': undefined local variable or method `abcd' for main:Object (NameError)
        from bin/console:24:in `rescue in block in <main>'
        from bin/console:16:in `block in <main>'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/sequel-5.50.0/lib/sequel/database/transactions.rb:258:in `_transaction'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/sequel-5.50.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/sequel-5.50.0/lib/sequel/database/transactions.rb:195:in `transaction'
        from bin/console:8:in `<main>'
/home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require': cannot load such file -- pry (LoadError)
Did you mean?  pty
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from bin/console:18:in `block in <main>'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/sequel-5.50.0/lib/sequel/database/transactions.rb:258:in `_transaction'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/sequel-5.50.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        from /home/deployer/apps/marketbet_crawler_production/shared/bundle/ruby/3.0.0/gems/sequel-5.50.0/lib/sequel/database/transactions.rb:195:in `transaction'
        from bin/console:8:in `<main>'
3.0.0 :002 > 
```

So, my issue is, is there a way to workaround this? or, how to use original not patched require instead?

**Comment by fxn** [comment]
The patched `require` is transparent, it calls the original `require` ([here](https://github.com/fxn/zeitwerk/blob/efc7ea74165289d02f6a7b0fd09988279224319e/lib/zeitwerk/kernel.rb#L35)). You can ignore that it shows in the backtrace, I bet your problem is elsewhere.

**Comment by fxn** [comment]
See

```
% irb
irb(main):001:0> require 'zeitwerk'
=> true
irb(main):002:0> require 'foo'
Traceback (most recent call last):
        7: from /var/folders/y9/6y6z18850vggvcnvv88vr55h0000gn/T/frum_2685_1637577948952/bin/irb:23:in `<main>'
        6: from /var/folders/y9/6y6z18850vggvcnvv88vr55h0000gn/T/frum_2685_1637577948952/bin/irb:23:in `load'
        5: from /Users/fxn/.frum/versions/2.6.8/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):2
        3: from /Users/fxn/.frum/versions/2.6.8/lib/ruby/gems/2.6.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        2: from /Users/fxn/.frum/versions/2.6.8/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        1: from /Users/fxn/.frum/versions/2.6.8/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
LoadError (cannot load such file -- foo)
```

**Comment by casperisfine** [comment]
Welcome to my world Xavier https://github.com/Shopify/bootsnap/blob/b718e075d6c6ac2a2a759860236676c24ae54e41/.github/issue_template.md?plain=1#L3-L5

😉

**Comment by fxn** [comment]
Haha

**Comment by zw963** [comment]
Yes, you are right, i try again with not load zeitwerk instead, get a similiar backtrace ... (do some simplify)

```
3.0.2 :001 > abcd
(irb):1:in `<main>': undefined local variable or method `abcd' for main:Object (NameError)
        from bin/console:24:in `rescue in block in <main>'
        from bin/console:17:in `block in <main>'
        from gems/sequel-5.50.0/lib/sequel/database/transactions.rb:258:in `_transaction'
        from gems/sequel-5.50.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
        from gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
        from gems/sequel-5.50.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        from gems/sequel-5.50.0/lib/sequel/database/transactions.rb:195:in `transaction'
        from bin/console:9:in `<main>'
<internal:/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- pry (LoadError)
Did you mean?  pty
        from <internal:/home/zw963/others/.rvm/rubies/ruby-3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from bin/console:19:in `block in <main>'
        from gems/sequel-5.50.0/lib/sequel/database/transactions.rb:258:in `_transaction'
        from gems/sequel-5.50.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
        from gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
        from gems/sequel-5.50.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        from gems/sequel-5.50.0/lib/sequel/database/transactions.rb:195:in `transaction'
        from bin/console:9:in `<main>'
3.0.2 :002 > 

```

Yes, my code is a little buggy, let me think about a more robust way to make console can work both with pry/irb.

Thank you very much.

**Comment by zw963** [comment]
There is no easy way to work around this, unless hack irb source code (i guess), so i give up, just leave it ....
another solution, is split into two file, bin/console + bin/irb,  not a big deal anyway.
