### ISSUE TITLE
Zeitwerk::NameError: wrong constant name inferred by Module from file

### ISSUE THREAD

**Issue by briannicholls** [fxn/zeitwerk#222]
Hello @fxn , I could not find any info on this, so thank you for your help!

After getting this error trying to deploy (dev server runs fine), I run `bin/rails zeitwerk:check` and get the following error referencing my initial migration, which creates a table called `roles`:

```bash
Zeitwerk::NameError: wrong constant name 20220107234410CreateRoles inferred by Module from file
Possible ways to address this:

  * Tell Zeitwerk to ignore this particular file.
  * Tell Zeitwerk to ignore one of its parent directories.
  * Rename the file to comply with the naming conventions.
  * Modify the inflector to handle this case.
  ```

The migration file itself is named `20220107234410_create_roles.rb`, and I tried renaming it with no luck. The contents also seem to be okay, standard Rails migration:

```ruby
class CreateRoles < ActiveRecord::Migration[7.0]
  def change
    create_table :roles do |t|
      t.string :name

      t.timestamps
    end
  end
end
```

I have to mention that this is a brand new Rails 7 project, except that I copied the files (models, views, controllers, migrations, routes) from an older project which used Rails 6.

Rails v7.0.3
Ruby 3.0.1p64

Please let me know if I can provide any more info. Thank you!

UPDATE:

I was able to get a stack trace as I noticed the error happens when running `rails s -e production`. It points to `/zeitwerk/loader.rb:336:in block in set_autoloads_in_dir`. Will post full trace below. Just to fix the error, I added `.rb` suffix to the `basename` variable on line 337 to pass the `if`, but I got the same error for another file (`application_controller.rb`) and so I stopped there.

```bash
brian > rails s -e production
=> Booting Puma
=> Rails 7.0.3 application starting in production 
=> Run `bin/rails server --help` for more startup options
Exiting
/home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:360:in rescue in block in set_autoloads_in_dir': wrong constant name 20220107234410CreateRoles inferred by Module from file (Zeitwerk::NameError)

  /home/brian/code/overwatch/overwatch_api/overwatch/app/db/migrate/20220107234410_create_roles.rb

Possible ways to address this:

  * Tell Zeitwerk to ignore this particular file.
  * Tell Zeitwerk to ignore one of its parent directories.
  * Rename the file to comply with the naming conventions.
  * Modify the inflector to handle this case.
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:336:in `block in set_autoloads_in_dir'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `ls'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:335:in `set_autoloads_in_dir'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:76:in `block in on_namespace_loaded'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:75:in `each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:75:in `on_namespace_loaded'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:60:in `block in on_dir_autoloaded'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:46:in `synchronize'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:46:in `on_dir_autoloaded'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:31:in `require'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:247:in `block (2 levels) in eager_load'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `ls'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:235:in `block in eager_load'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:220:in `synchronize'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:220:in `eager_load'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:319:in `each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:319:in `eager_load_all'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `run'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/application.rb:372:in `initialize!'
        from /home/brian/code/overwatch/overwatch_api/overwatch/config/environment.rb:5:in `<main>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:312:in `block in start'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:379:in `handle_profiling'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:311:in `start'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:38:in `start'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:143:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:134:in `perform'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
/home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:121:in `const_defined?': wrong constant name 20220107234410CreateRoles (NameError)
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:121:in `cdef?'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:411:in `autoload_file'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:340:in `block in set_autoloads_in_dir'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `ls'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:335:in `set_autoloads_in_dir'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:76:in `block in on_namespace_loaded'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:75:in `each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:75:in `on_namespace_loaded'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:60:in `block in on_dir_autoloaded'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:46:in `synchronize'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:46:in `on_dir_autoloaded'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:31:in `require'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:247:in `block (2 levels) in eager_load'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `ls'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:235:in `block in eager_load'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:220:in `synchronize'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:220:in `eager_load'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:319:in `each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:319:in `eager_load_all'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:32:in `run'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/application.rb:372:in `initialize!'
        from /home/brian/code/overwatch/overwatch_api/overwatch/config/environment.rb:5:in `<main>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `eval'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:116:in `new_from_string'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:105:in `load_file'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:66:in `parse_file'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:249:in `app'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:422:in `wrapped_app'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:312:in `block in start'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:379:in `handle_profiling'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/server.rb:311:in `start'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:38:in `start'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:143:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:134:in `perform'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /home/brian/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by briannicholls** [comment]
In my ignorance, I didn't think it would be wise to ignore the `dm/migrate` folder, but I added the entire folder to Zeitwerk's ignore list and that did the trick. Now I am seeing that I have an issue connecting to the DB which is a fixable issue. Sorry for the false alarm!

```ruby
# config/initializers/zeitwerk.rb
Rails.autoloaders.main.ignore(
  "app/db/migrate"
)
```

**Comment by fxn** [comment]
Just in case, let me tell you that is very unusual.

Migrations don't go to `#{Rails.root}/app/db/migrations`, they go under `#{Rails.root}/db/migrations`, and you don't need to ignore that directory. Maybe you copied them in the wrong place?
