### ISSUE TITLE
Failing with extension gem

### ISSUE THREAD

**Issue by dukex** [fxn/zeitwerk#48]
Hi folks,

Given I have a extension gem (using dashes in the name), for example `my-gem`(`My::Gem`), how to correct setup the zeitwerk? 

I made the following test and it's failing!

```ruby
    files = [
      ["my/gem.rb", <<-EOS],
        $for_gem_test_loader = Zeitwerk::Loader.for_gem
        $for_gem_test_loader.enable_reloading
        $for_gem_test_loader.setup

        module My
          module Gem
          end
        end
      EOS
      ["my/gem/foo.rb", "class My::Gem::Foo; end"],
      ["my/gem/foo/bar.rb", "class My::Gem::Foo::Bar; end"]
    ]
    with_files(files) do
      with_load_path(".") do
        assert require "my/gem"
        assert My::Gem::Foo::Bar

        $for_gem_test_loader.unload
        assert !Object.const_defined?(:My::Gem)

        $for_gem_test_loader.setup
        assert My::Gem::Foo::Bar
      end
    end
```

```bash
% rake test                                                                                                                                                  *master zeitwerk

# Running tests with run options --seed 48021:

......................................................................E..........................................................................

Finished tests in 1.354945s, 107.0154 tests/s, 249.4567 assertions/s.


Error:
TestForGem#test_sets_my_gem_correctly:
NameError: uninitialized constant My::Gem::Foo
    /home/duke/src/oss/zeitwerk/test/lib/zeitwerk/test_for_gem.rb:49:in `block (3 levels) in <class:TestForGem>'
    /home/duke/src/oss/zeitwerk/test/support/loader_test.rb:70:in `with_load_path'
    /home/duke/src/oss/zeitwerk/test/lib/zeitwerk/test_for_gem.rb:47:in `block (2 levels) in <class:TestForGem>'
    /home/duke/src/oss/zeitwerk/test/support/loader_test.rb:61:in `block in with_files'
    /home/duke/src/oss/zeitwerk/test/support/loader_test.rb:54:in `chdir'
    /home/duke/src/oss/zeitwerk/test/support/loader_test.rb:54:in `with_files'
    /home/duke/src/oss/zeitwerk/test/lib/zeitwerk/test_for_gem.rb:46:in `block in <class:TestForGem>'

145 tests, 338 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1)

Tasks: TOP => test
(See full trace by running task with --trace)

```

Can somebody help me to understand why zeitwerk aren't working? I'm making something wrong or it's a bug?

**Comment by fxn** [comment]
Yeah, `for_gem` is a shortcut that assumes basically this structure:

```
lib/my_gem.rb
lib/my_gem/version.rb
lib/my_gem/my_class.rb
...
```

so in your case you need to setup the loader using the generic API.

That would be something like (off the top of my head):

```ruby
require "zeitwerk"

loader = Zeitwerk::Loader.new
loader.push_dir("#{__dir__}/..") # absolute path to lib directory
loader.tag = 'my-gem' # convenient for debugging
loader.setup
loader.eager_load # if you want to eager load
```

If you have `version.rb`, you may need to define an inflector too:

```ruby
inflector = Class.new(Zeitwerk::Inflector) do
  def camelize(basename, _abspath)
    basename == 'version' ? 'VERSION' : super
  end
end.new

loader.inflector = inflector
```
