### ISSUE TITLE
Error running an example from synopsis

### ISSUE THREAD

**Issue by bruno-** [fxn/zeitwerk#78]
Hi,

I'm playing with this gem by running an example from synopsis:

```ruby
# lib/my_gem.rb
require "zeitwerk"
loader = Zeitwerk::Loader.for_gem
loader.setup

module MyGem
end

loader.eager_load
```

By running `ruby lib/my_gem.rb` I'm getting the below error.

- `ruby --version`: `ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin17]`
- `gem list zeitwerk`: `zeitwerk (2.1.9)`

Am I doing something wrong? Thanks!

```
Traceback (most recent call last):                 
        14: from lib/my_gem.rb:5:in `<main>'       
        13: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/kernel.rb:16:in `require'
        12: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        11: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        10: from /Users/bruno/data/edu/project/lib/my_gem.rb:2:in `<top (required)>'                  
         9: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:442:in `for_gem'
         8: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/registry.rb:85:in `loader_for_gem'
         7: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/registry.rb:85:in `tap'
         6: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/registry.rb:88:in `block in loader_for_gem'
         5: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:182:in `push_dir'
         4: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:713:in `raise_if_conflicting_directory'
         3: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:713:in `synchronize'
         2: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:714:in `block in raise_if_conflicting_directory'
         1: from /Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:714:in `each'
/Users/bruno/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/zeitwerk-2.1.9/lib/zeitwerk/loader.rb:717:in `block (2 levels) in raise_if_conflicting_directory': loader (Zeitwerk::Error)

#<Zeitwerk::Loader:0x00007fbf270f66d8
 @autoloaded_dirs=[],
 @autoloads={},
 @eager_load_exclusions=#<Set: {}>,
 @eager_loaded=false,
 @ignored_glob_patterns=#<Set: {}>,
 @ignored_paths=#<Set: {}>,
 @inflector=
  #<Zeitwerk::GemInflector:0x00007fbf270f61b0
   @version_file="/Users/bruno/data/edu/project/lib/my_gem/version.rb">,
 @initialized_at=2019-09-01 00:56:45 +0200,
 @lazy_subdirs={},
 @logger=nil,
 @mutex=#<Thread::Mutex:0x00007fbf270f6250>,
 @mutex2=#<Thread::Mutex:0x00007fbf270f6200>,
 @preloads=[],
 @reloading_enabled=false,
 @root_dirs={},
 @setup=false,
 @tag="my_gem",
 @to_unload={}>


wants to manage directory /Users/bruno/data/edu/project/lib, which is already managed by

#<Zeitwerk::Loader:0x00007fbf2710d978
 @autoloaded_dirs=[],
 @autoloads=
  {"/Users/bruno/data/edu/project/lib/my_gem.rb"=>[Object, :MyGem],
   "/Users/bruno/data/edu/project/lib/project"=>[Object, :Project]},
 @eager_load_exclusions=#<Set: {}>,
 @eager_loaded=false,
 @ignored_glob_patterns=#<Set: {}>,
 @ignored_paths=#<Set: {}>,
 @inflector=
  #<Zeitwerk::GemInflector:0x00007fbf2710d0e0
   @version_file="lib/my_gem/version.rb">,
 @initialized_at=2019-09-01 00:56:45 +0200,
 @lazy_subdirs={"Project"=>["/Users/bruno/data/edu/project/lib/project"]},
 @logger=nil,
 @mutex=#<Thread::Mutex:0x00007fbf2710d220>,
 @mutex2=#<Thread::Mutex:0x00007fbf2710d1d0>,
 @preloads=[],
 @reloading_enabled=false,
 @root_dirs={"/Users/bruno/data/edu/project/lib"=>true},
 @setup=true,
 @tag="my_gem",
 @to_unload={}>
```

**Comment by byroot** [comment]
Are you running it with `ruby lib/my_gem.rb`? Because that's how I managed to reproduce your backtrace.

I'll dig a bit to see if that case could be supported, or at least properly detected, but gems aren't supposed to be loaded this way, this is why it breaks.

In the meantime for your tests your should use a distinct entry point, e.g:

```ruby
# in: bin/run
#!/usr/bin/env ruby

require_relative '../../lib/my_gem.rb'
```

**Comment by byroot** [comment]
Fix is here: https://github.com/fxn/zeitwerk/pull/79

**Comment by bruno-** [comment]
> Are you running it with ruby lib/my_gem.rb?

Yep, that's what I'm using.

**Comment by fxn** [comment]
This is not going to be supported, I have documented idiomatic ways to do this in the pull request.
